# Generated by Django 5.0 on 2023-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(default='DEFAULT_VALUE', max_length=10, verbose_name='Placa do carro'),
        ),
    ]
