# Generated by Django 5.0 on 2023-12-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_carro_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
